<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="Shared.props" />

  <PropertyGroup>
    <AssemblyName>7Bpencil.ChangeVersionLabel</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" />
    <Reference Include="SPTushonka.Reflection" />
    <Reference Include="Assembly-CSharp" />
    <Reference Include="BepInEx.Core" />
    <Reference Include="BepInEx.Unity.IL2CPP" />
    <Reference Include="Il2Cppmscorlib" />
    <Reference Include="Il2CppInterop.Runtime" />
    <Reference Include="Sirenix.Serialization" />
    <Reference Include="UnityEngine" />
    <Reference Include="UnityEngine.CoreModule" />
  </ItemGroup>

</Project>
